### ISSUE TITLE
关于相同种子下多次运行结果不一致的问题

### ISSUE THREAD

**Issue by Ottehack** [chiayewken/Span-ASTE#10]
作者你好，我最近按照readme里面的流程跑了这个项目，我也看到论文中说结果是五个种子的平均结果，但是我在重复对同一个数据集在完全同样的参数设置（包括随机种子）下跑出来的结果是不一样的，上下有1左右的浮动，我对allennlp了解的不是很多，所以想请教一下你是否思考过原因。

**Comment by chiayewken** [comment]
Hi, there is some randomness that cannot be removed as some modules in AllenNLP are non-deterministic. For example, I tried torch.use_deterministic_algorithms() but this causes an error as some operations cannot be fully deterministic. Due to time constraint, I did not explore deeply in this area, but the experimental result variation should be acceptable when considering the size of the dataset.
